### ISSUE TITLE
Remove dependency on jQuery

### ISSUE THREAD

**Issue by SBRK** [micronull/thumbnail-youtube-vimeo#1]
I'm getting ` ReferenceError: $ is not defined`, so I'm assuming this package assumes jQuery is loaded... I don't want to add jQuery just for using this package. Using fetch would be much simpler than relying on jQuery.

**Comment by micronull** [comment]
Thanks!

**Comment by SBRK** [comment]
@De-Luxis no problem. Could you publish on NPM so that I don't have to use my repo on my package.json ?

**Comment by micronull** [comment]
@SBRK Published.
